### ISSUE TITLE
Desktop file integration not quite working on Gnome

### ISSUE THREAD

**Issue by takluyver** [CamielBouchier/cb_thunderlink#26] opened 2021-01-26 12:23 UTC
Hi! Thanks for this extension.

I got some errors trying to register the desktop integration on Fedora 33, and mostly just wanted to record them while I can still find them easily:

```
Executing ['gio', 'mime', 'x-scheme-handler/cbthunderlink', 'cb_thunderlink_cbthunderlink.desktop']
gio: Failed to load info for handler “cb_thunderlink_cbthunderlink.desktop”
(b'', None)
Writing /home/takluyver/.local/share/applications/cb_thunderlink_thunderlink.desktop
Executing ['gio', 'mime', 'x-scheme-handler/thunderlink', 'cb_thunderlink_thunderlink.desktop']
gio: Failed to load info for handler “cb_thunderlink_thunderlink.desktop”
(b'', None)
```

I can use the URLs with `python3 cb_thunderlink.py <url>`, but `xdg-open <url>` fails with:

```
gio: <url>: The specified location is not supported
```

This is the same for both cbthunderlink:// and thunderlink:// URLs.

**Comment by CamielBouchier** [comment] 2021-01-27 00:07
Just acknowledging I saw the report which seems pretty clear to me.
This must be an issue with the integration under Fedora 33, but I can't spot at once.
I will have a look, probably in the weekend.

Camiel B.

**Comment by CamielBouchier** [comment] 2021-01-27 00:17
Can you share the contents of the "*.desktop" file referred into the output?

Also, can you manually execute `gio mime x-scheme-handler/cbthunderlink cb_thunderlink_cbthunderlink.desktop` and post the output?

Camiel B.

**Comment by takluyver** [comment] 2021-01-27 08:58
Sure! Here's the contents of one of the files (the other one is similar):

```ini
[Desktop Entry]
Encoding=UTF-8
Name=cb_thunderlink_thunderlink
Exec=/home/takluyver/Code/cb_thunderlink/cb_thunderlink.py %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=thunderbird
Categories=Application;Network;Email;
MimeType=x-scheme-handler/thunderlink;
StartupNotify=true
Actions=Compose;Contacts
NoDisplay=true
```

When I ran the `gio mime` command this morning, it worked (output: `Set cb_thunderlink_cbthunderlink.desktop as the default for x-scheme-handler/cbthunderlink`). After that, xdg-open is working. :slightly_smiling_face: 

I wonder if Gnome is caching the desktop files, and by the time I came to run the command this morning, it had noticed the new ones? I found a command `update-desktop-database` which initially seemed relevant, but the output file described in its man page (`~/.local/share/applications/mimeinfo.cache`) doesn't contain any thunderlink entries, even after I've got this working, so possibly Gnome has something similar somewhere else.

**Comment by CamielBouchier** [comment] 2021-01-27 17:19
@takluyver 
Thanks for the feedback. That seems weird ... 
Does the `gio mime ...` command also run correctly when using the script?
(I'd rather think about some shell related problem, but currently it is just the better guessing work ...)

**Comment by takluyver** [comment] 2021-01-27 17:25
Yup, if I run the script again, it's working now:
```
Executing ['gio', 'mime', 'x-scheme-handler/cbthunderlink', 'cb_thunderlink_cbthunderlink.desktop']
(b'Set cb_thunderlink_cbthunderlink.desktop as the default for x-scheme-handler/cbthunderlink\n', None)
Writing /home/takluyver/.local/share/applications/cb_thunderlink_thunderlink.desktop
Executing ['gio', 'mime', 'x-scheme-handler/thunderlink', 'cb_thunderlink_thunderlink.desktop']
(b'Set cb_thunderlink_thunderlink.desktop as the default for x-scheme-handler/thunderlink\n', None
```


I can try removing the files, waiting a bit and then running the script again if there's anything we want to investigate.

**Comment by CamielBouchier** [comment] 2021-01-27 20:15
I can't reproduce either ...
So unless you can reproduce and find something to investigate further upon, I will close this "soon".
Camiel B.

**Comment by takluyver** [comment] 2021-01-28 17:04
I've deleted the files, I'm going to try again after I next restart, and see if it happens again.

I also just spotted that you could probably install just one .desktop file, as `MimeType` can specify more than one option. E.g. Firefox on my system has:

```ini
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
```

**Comment by takluyver** [comment] 2021-01-29 14:45
Today it installed correctly, so it seems I can't reproduce it. :confused:

**Comment by CamielBouchier** [comment] 2021-01-29 16:55
So I guess I can close this issue for now. 
Let me know if there would need more help.
Camiel B,

**Closed by CamielBouchier** 2021-01-29 16:55 UTC
